### ISSUE TITLE
Support for Rails 4 

### ISSUE THREAD

**Issue by deberle** [djberg96/sys-memory#2]
I would love to use this tool in my legacy rails app which is still  at version 4.2. 
I get the following output when running bundler

```
      Bundler could not find compatible versions for gem "activesupport":
      [...]
      rails (~> 4.2.0) was resolved to 4.2.10, which depends on
        activesupport (= 4.2.10)
      sys-memory was resolved to 0.1.0, which depends on
        activesupport (~> 6.0)
```

Is it possible to relax the active support version in this project?

**Comment by djberg96** [comment]
Hm, I think it's only supposed to be a development dependency anyway, but let me double check.

**Comment by djberg96** [comment]
https://github.com/djberg96/sys-memory/pull/3

**Comment by djberg96** [comment]
@deberle I pushed out 0.1.1 just now with the update. Thanks for the report!

**Comment by deberle** [comment]
Awesome, thanks a lot for your work!
